# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd200b080fe3b6c67b0960108c246f624d913883ccb87e5e66119729255f04526be1522945d13c9feb392d6fe61c7bad71855f9fefbbaebbcd5c0690e31b6127

test:
  secret_key_base: cc0b7a73f2acfbc168a6ae5d8407d1f39d437f8f4d12b4bdebc408d24bb9bf58e76f98883a6bf0d910fa15e92712b11daf0058521ece136039b44a3030ffb0a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
